### ISSUE TITLE
Pretrained weights link cannot be accessed

### ISSUE THREAD

**Issue by csu-roycheng** [YAIxPOZAlabs/MuseDiffusion#76]
Hi, I'm very interested in your work, and I want to use your pretrained weights, but found the link is broken, 
can you update the link of pretrained weights?

**Comment by csu-roycheng** [comment]
I found it can be download in releases, however the link in readme can not be accessed.

**Comment by kdha0727** [comment]
I see. Thank you for notifying. The link will be updated soon.
