### ISSUE TITLE
logic behind metric.py

### ISSUE THREAD

**Issue by iamamiramine** [YAIxPOZAlabs/MuseDiffusion#78]
I am trying to understand how metric.py works.

First of all, I want to ask how are the input MIDI files represented? Are they encoded into REMI and extended to include the ComMu metadata? Or are they RAW MIDIs with the metadata?

Second question, in the `get_vectors` function, what does `if midi[i] <= 2` correspond to?

**Comment by kdha0727** [comment]
Hi, 

The `metric.py` file is used in [`MuseDiffusion.run.sample`](https://github.com/YAIxPOZAlabs/MuseDiffusion/blob/ef8fe3059f31ce4f1a6e0632909e6186da1fba86/MuseDiffusion/run/sample.py#L245). (refer the link)

First, MIDI files for metric argument don't include the metadata. It is embedded vector, and the metadata is separated by the function. ([refer this permalink](https://github.com/YAIxPOZAlabs/MuseDiffusion/blob/ef8fe3059f31ce4f1a6e0632909e6186da1fba86/MuseDiffusion/run/sample.py#L255:L262))

Second, `midi[i]` represents each embedding value, and `midi[i] <= 2` corresponds to the meaningless tokens.

**Comment by kdha0727** [comment]
Hi, 

The `metric.py` file is used in [`MuseDiffusion.run.sample`](https://github.com/YAIxPOZAlabs/MuseDiffusion/blob/ef8fe3059f31ce4f1a6e0632909e6186da1fba86/MuseDiffusion/run/sample.py#L245). (refer the link)

First, MIDI files for metric argument don't include the metadata. It is embedded vector, and the metadata is separated by the function. ([refer this permalink](https://github.com/YAIxPOZAlabs/MuseDiffusion/blob/ef8fe3059f31ce4f1a6e0632909e6186da1fba86/MuseDiffusion/run/sample.py#L255:L262))

Second, `midi[i]` represents each embedding value, and `midi[i] <= 2` corresponds to the meaningless tokens.
